---
title: "FPD"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(scales)
library(lubridate)
library(tidyr)
```

```{r data}
# doesn't work without a csv
delsrmd <- read.csv("C:/Users/josefina.simkova/Documents/R/Delinquents/dels2.csv")

```


```{r, include=FALSE}
Sys.setlocale("LC_ALL", "English")
```


```{css}
.chart-shim {
  position: relative !important;
  margin-bottom: 8px;
}

```

# Monthly {.tabset}


Column {data-width=400}
-----------------------------------------------------------------------

### New clients 


#### Based on due date
##### Count
```{r}

fpd_order <- c("fpd5", "fpd30", "fpd90")

a1<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(due_date), "month"), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(month)

b1<-delsrmd %>% 
  filter(client_type == 'NEW' & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(due_date), "month")) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(month)

data1 <-a1 %>% 
  right_join(.,b1, by = 'month') %>% 
  filter(month <= Sys.Date()) %>% 
  mutate(pct = n/total)

custom_lims1 <- c(0, max(data1$pct) +0.1)


renderPlotly({
  ch1 <- data1 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims1,
                       breaks = seq(0, custom_lims1[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch1 %>% ggplotly(tooltip = "text")
})
```

##### Amount
```{r}

a2<-delsrmd %>%
  filter(client_type == 'NEW' & !is.na(fpd_grp) & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>%
  group_by(month = lubridate::floor_date(as.Date(due_date), "month"), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(month)

b2<-delsrmd %>%
  filter(client_type == 'NEW' & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>%
  group_by(month = lubridate::floor_date(as.Date(due_date), "month")) %>%
 dplyr::summarise(total = sum(amount)) %>%
 arrange(month)

data2 <-a2 %>%
  right_join(.,b2, by = 'month') %>%
  filter(month <= Sys.Date()) %>%
  mutate(pct = amount/total)

custom_lims2 <- c(0, max(data2$pct) +0.1)


renderPlotly({
  ch2 <- data2 %>%
    ggplot(
        (aes(x = month,
             y = pct,
             group = fpd_grp,
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims2,
                       breaks = seq(0, custom_lims2[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch2 %>% ggplotly(tooltip = "text")
})
###
```

#### Based on loan entity created
##### Count
```{r}
a3<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month"), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(month)

b3<-delsrmd %>% 
  filter(client_type == 'NEW' & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month")) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(month)

data3 <-a3 %>% 
  right_join(.,b3, by = 'month') %>% 
  filter(month <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims3 <- c(0, max(data3$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch3 <- data3 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims3,
                       breaks = seq(0, custom_lims3[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch3 %>% ggplotly(tooltip = "text")
})
```


##### Amount
```{r}
a4<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month"), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>% 
  arrange(month)

b4<-delsrmd %>% 
  filter(client_type == 'NEW' & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month")) %>% 
 dplyr::summarise(total = sum(amount)) %>% 
 arrange(month)

data4 <-a4 %>% 
  right_join(.,b4, by = 'month') %>% 
  filter(month <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims4 <- c(0, max(data4$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch4 <- data4 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims4,
                       breaks = seq(0, custom_lims4[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch4 %>% ggplotly(tooltip = "text")
})
```


Column {data-width=400}
-----------------------------------------------------------------------
### Returning clients
#### Based on due date
##### Count
```{r}
a5<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(due_date), "month"), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(month)

b5<-delsrmd %>% 
  filter(client_type == 'RETURNING' & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(due_date), "month")) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(month)

data5 <-a5 %>% 
  right_join(.,b5, by = 'month') %>% 
  filter(month <= Sys.Date()) %>% 
  mutate(pct = n/total)

custom_lims5 <- c(0, max(data5$pct) +0.01)


renderPlotly({
  ch5 <- data5 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims5,
                       breaks = seq(0, custom_lims5[2], .05),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch5 %>% ggplotly(tooltip = "text")
})
```

##### Amount
```{r}
a6<-delsrmd %>%
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>%
  group_by(month = lubridate::floor_date(as.Date(due_date), "month"), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(month)

b6<-delsrmd %>%
  filter(client_type == 'RETURNING' & rollback(as.Date(due_date), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>%
  group_by(month = lubridate::floor_date(as.Date(due_date), "month")) %>%
 dplyr::summarise(total = sum(amount)) %>%
 arrange(month)

data6 <-a6 %>%
  right_join(.,b6, by = 'month') %>%
  filter(month <= Sys.Date()) %>%
  mutate(pct = amount/total)

custom_lims6 <- c(0, max(data6$pct) +0.1)


renderPlotly({
  ch6 <- data6 %>%
    ggplot(
        (aes(x = month,
             y = pct,
             group = fpd_grp,
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims6,
                       breaks = seq(0, custom_lims6[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch6 %>% ggplotly(tooltip = "text")
})
```

#### Based on loan entity created
##### Count
```{r}
a7<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month"), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(month)

b7<-delsrmd %>% 
  filter(client_type == 'RETURNING' & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month")) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(month)

data7 <-a7 %>% 
  right_join(.,b7, by = 'month') %>% 
  filter(month <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims7 <- c(0, max(data7$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch7 <- data7 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims7,
                       breaks = seq(0, custom_lims7[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch7 %>% ggplotly(tooltip = "text")
})
```

##### Amount
```{r}
a8<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month"), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>% 
  arrange(month)

b8<-delsrmd %>% 
  filter(client_type == 'RETURNING' & rollback(as.Date(loan_entity_created), roll_to_first = TRUE) > rollback(as.Date(Sys.Date()), roll_to_first = TRUE) %m-% months(12)) %>% 
  group_by(month = lubridate::floor_date(as.Date(loan_entity_created), "month")) %>% 
 dplyr::summarise(total = sum(amount)) %>% 
 arrange(month)

data8 <-a8 %>% 
  right_join(.,b8, by = 'month') %>% 
  filter(month <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims8 <- c(0, max(data8$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch8 <- data8 %>%
    ggplot(
        (aes(x = month, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "Month: ", format(month, '%b %Y'),
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('month')
                 , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "Month") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims8,
                       breaks = seq(0, custom_lims8[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch8 %>% ggplotly(tooltip = "text")
})
```

# Weekly
Column {data-width=400}
-----------------------------------------------------------------------
### New clients 
#### Based on due date
##### Count
```{r}

a9<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(week)

b9<-delsrmd %>% 
  filter(client_type == 'NEW' & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1)) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(week)

data9 <-a9 %>% 
  right_join(.,b9, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims9 <- c(0, max(data9$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch9 <- data9 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims9,
                       breaks = seq(0, custom_lims9[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch9 %>% ggplotly(tooltip = "text")
})
```
##### Amount
```{r}

a10<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(week)

b10<-delsrmd %>% 
  filter(client_type == 'NEW' & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1)) %>% 
 dplyr::summarise(total = sum(amount)) %>%
 arrange(week)

data10 <-a10 %>% 
  right_join(.,b10, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims10 <- c(0, max(data10$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch10 <- data10 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
              "Week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims10,
                       breaks = seq(0, custom_lims10[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch10 %>% ggplotly(tooltip = "text")
})
```

#### Based on loan entity created
##### Count
```{r}

a11<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(week)

b11<-delsrmd %>% 
  filter(client_type == 'NEW' & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1)) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(week)

data11 <-a11 %>% 
  right_join(.,b11, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims11 <- c(0, max(data11$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch11 <- data11 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims11,
                       breaks = seq(0, custom_lims11[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch11 %>% ggplotly(tooltip = "text")
})
```

##### Amount
```{r}

a12<-delsrmd %>% 
  filter(client_type == 'NEW' & !is.na(fpd_grp) & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(week)

b12<-delsrmd %>% 
  filter(client_type == 'NEW' & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1)) %>% 
 dplyr::summarise(total = sum(amount)) %>%
 arrange(week)

data12 <-a12 %>% 
  right_join(.,b12, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims12 <- c(0, max(data12$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch12 <- data12 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
              "Week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims12,
                       breaks = seq(0, custom_lims12[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch12 %>% ggplotly(tooltip = "text")
})
```
Column {data-width=400}
-----------------------------------------------------------------------
### Returning clients 
#### Based on due date
##### Count
```{r}

a13<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(week)

b13<-delsrmd %>% 
  filter(client_type == 'RETURNING' & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1)) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(week)

data13 <-a13 %>% 
  right_join(.,b13, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims13 <- c(0, max(data13$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch13 <- data13 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims13,
                       breaks = seq(0, custom_lims13[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch13 %>% ggplotly(tooltip = "text")
})
```
##### Amount
```{r}

a14<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(week)

b14<-delsrmd %>% 
  filter(client_type == 'RETURNING' & floor_date(as.Date(due_date), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(due_date), "week", week_start = 1)) %>% 
 dplyr::summarise(total = sum(amount)) %>%
 arrange(week)

data14 <-a14 %>% 
  right_join(.,b14, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims14 <- c(0, max(data14$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch14 <- data14 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
              "Week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims14,
                       breaks = seq(0, custom_lims14[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch14 %>% ggplotly(tooltip = "text")
})
```
#### Based on loan entity created
##### Count
```{r}

a15<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(n = n()) %>% 
  arrange(week)

b15<-delsrmd %>% 
  filter(client_type == 'RETURNING' & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1)) %>% 
 dplyr::summarise(total = n()) %>% 
 arrange(week)

data15 <-a15 %>% 
  right_join(.,b15, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = n/total)

custom_lims15 <- c(0, max(data15$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch15 <- data15 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
               "week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "n: ", n,
               "<br>",
               "Total: ", total,
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims15,
                       breaks = seq(0, custom_lims15[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch15 %>% ggplotly(tooltip = "text")
})
```
##### Amount
```{r}

a16<-delsrmd %>% 
  filter(client_type == 'RETURNING' & !is.na(fpd_grp) & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1), fpd_grp) %>%
  dplyr::summarise(amount = sum(amount)) %>%
  arrange(week)

b16<-delsrmd %>% 
  filter(client_type == 'RETURNING' & floor_date(as.Date(loan_entity_created), unit = "week", week_start = 1) > floor_date(Sys.Date(), unit = "week", week_start = 1) -dweeks(20)) %>% 
  group_by(week = lubridate::floor_date(as.Date(loan_entity_created), "week", week_start = 1)) %>% 
 dplyr::summarise(total = sum(amount)) %>%
 arrange(week)

data16 <-a16 %>% 
  right_join(.,b16, by = 'week') %>% 
  filter(week <= Sys.Date(), !is.na(fpd_grp)) %>% 
  mutate(pct = amount/total)

custom_lims16 <- c(0, max(data16$pct, na.rm = TRUE) +0.1)


renderPlotly({
  ch16 <- data16 %>%
    ggplot(
        (aes(x = week, 
             y = pct, 
             group = fpd_grp, 
             color = factor(fpd_grp, fpd_order),
             text = paste0(
              "Week: ", week,
               "<br>",
               "Pct: ", scales::percent(pct, accuracy = .01),
               "<br>",
               "Amount: ", format(amount, big.mark = ","), "CZK",
               "<br>",
               "Total amount: ", format(total, big.mark = ","), "CZK",
               "<br>",
               "FPD group: ", fpd_grp)
             ))) +
    geom_line() +
    scale_x_date(breaks = date_breaks('2 week')
                 # , labels = date_format('%b %Y')
                 , minor_breaks = NULL
                 ,name = "week") +
    geom_point()+
    scale_y_continuous(labels = scales::percent,
                       limits = custom_lims16,
                       breaks = seq(0, custom_lims16[2], .1),
                       name = "Percentage", expand = c(0,0), minor_breaks = NULL)+
    scale_color_discrete(breaks = fpd_order, name = "FPD group")+
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

  ch16 %>% ggplotly(tooltip = "text")
})
```